version: 2.1
jobs:
  build_and_test:
    parameters:
      compiler:
        description: C++ compiler to build with
        type: string
      standard:
        description: C++ standard to build with
        type: string
      mode:
        description: mode to build and test with
        type: string
    machine:
      image:  ubuntu-2004:202201-02
    resource_class: large
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: echo 'docker run --pids-limit -1 --security-opt seccomp=unconfined --network host --user "$(id -u):$(id -g)" --rm -v $PWD:$PWD -w $PWD  docker.io/scylladb/seastar-toolchain:2023-08-13 "$@"' > run; chmod +x run
      - run:
          command: |
            ./run ./configure.py --compiler << parameters.compiler >> --c++-standard << parameters.standard >>
            if [ << parameters.mode >> = "dev" ]; then
              ./run ninja -C build/<< parameters.mode >> all checkheaders
            else
              ./run ninja -C build/<< parameters.mode >>
            fi
            ./run ./test.py --mode=<< parameters.mode >>

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              compiler: ["clang++-15", "g++-12"]
              standard: ["20", "17"]
              mode: ["dev", "debug", "release"]
